#TODO:
#hostmanager

version: '2'

services:
  apache-php:
    build: ./apache-php
    networks:
      static-network:
    volumes:
      - ./repositories/shopware:/var/www/shopware
      - ./apache-php/logs:/var/log/apache-php
      - ./repositories/themes/Custom:/var/www/shopware/themes/Frontend/Custom
      - ./repositories/plugins:/var/www/shopware/engine/Shopware/Plugins/Local
      - ./apache-php/logs/apache2:/var/log/apache2
      - ./repositories/plugins5.2:/var/www/shopware/custom/plugins

  db:
    image: mysql:5.7
    networks:
      static-network:
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: shopware
    volumes:
      - ./db-dump:/docker-entrypoint-initdb.d
      - ./scripts:/usr/local/bin/export

networks:
  static-network:
    driver: bridge
    ipam:
     config:
       - subnet: 172.10.0.0/16
         gateway: 172.10.5.254
         aux_addresses:
          apache-php: 172.10.1.2
          db: 172.10.1.3
          phpmyadmin: 172.10.1.4
