#TODO:
#add repositories: plugins, themes
#link repositories to folder
#import and export dump
#install extensions
#logs for container to host
#log-folder to gitignore
#resolve servername

version: '2'

services:
  apache-php:
    build: ./apache-php
    networks:
      static-network:
        ipv4_address: 172.20.128.2
    volumes:
      - ./repositories/shopware:/var/www/shopware
      - ./apache-php/logs:/var/logs/apache-php

  db:
    image: mysql
    networks:
      static-network:
        ipv4_address: 172.20.128.3
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: dev
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: shopware

networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
          ip_range: 172.28.5.0/24
